language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install --prefix client
script:
  - echo "Running tests against $(node -v)..."
  - npm test -- --coverage
  - codecov
  # - npm run deploy
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
