language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  local_dir: build
  api_key:
    secure: HqOF1pzqTqyyIzJIceQZoWQBWRwrLBw51mnh0PNXbKqGqHyKndCZWRyPQ/zyCVtKgT2lhEfmWaYChm/EHMA8boiZnFQAqFA905WWqdbd2Uik3974KT9qlHPXw/Bo5+BCrT5lXZTpDIil8JFwyRW6PlBJAiaHj/TRWV+ki/hsjzrMN6LXJKDXnpPl2duairI6vsWtpUk+mDu/6N4xFWAmtdQNA4nyftY4IOBskwhLMwm5D83SZzKRwxt01dty6xLvVc6h3xNqLUT1d5xq6nAqZL7mkJedf7NY8sXoXV6xglCYBwuZy6UZDB4I4bNM9kGY6xnTC/vdTcfbhBCVZZy4SvvQBE3Wru7enusXXSfiUxdWn64YS1x+hg0QQM16YOm4+BQIXfKXL5LQ0+CSRikehjvv7hOPONwuTFOrAMREp9zSIwNGkjAQPjySnHzSAiKy3F7aT4SmZbDHF9RcH+qR31uyjvK0P6Ep4xGXlto3HTZuW++R0PbYDii8tWgRGrJ6yzKYa9uOfneaC1ifTx1eNqJpT4SQpQeLE+XqGogu7NCGhfYqy8wDLlJi6Sxu9QGsXWsCdBxg17YDlQ6DexSLD9iYoR7XLgooTGtuf5x9hqGB7sL3PrsOoMpBHyyARKAlwm2JuEIYpm2STvi2X97BCs2UMmF1FAGWd4U7ZFdo2oM=
  strategy: git
