language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
script:
  - npm run deploy
  - echo "Running tests against $(node -v)..."
  - npm test -- --coverage
  - codecov
