language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - yarn global add codecov
  - yarn --prefix client
script:
  - echo "Running tests against $(node -v)..."
  - yarn test -- --coverage
  - codecov
  # - yarn run deploy
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
