environment:
  nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install --prefix client

test_script:
  - node --version
  - npm --version
  - npm test

build: off
