export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD = 'ADD';
export const SUBTRACT = 'SUBTRACT';
export const STORE_RESULT = 'STORE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const SET_EXPENSES = 'SET_EXPENSES';

export const SET_END_DATE = 'SET_END_DATE';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_TEXT = 'SET_TEXT';
export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT';
export const SORT_BY_DATE = 'SORT_BY_DATE';
// export const  = '';
export const ORDERS_FETCH_START = 'ORDERS_FETCH_START';
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS';
export const ORDERS_FETCH_FAILED = 'ORDERS_FETCH_FAILED';
